<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $gen->job_role }} — KRA / KPI</title>
    <style>
        body{font-family: DejaVu Sans, sans-serif; color:#1f2a44; font-size:11px; line-height:1.45;}
        h1{font-size:18px;margin:0 0 4px;color:#6d28d9;}
        h2{font-size:13px;margin:16px 0 8px;color:#1f2a44;}
        .sub{color:#64748b;font-size:10px;margin-bottom:14px;}
        .meta{width:100%;border-collapse:collapse;margin-bottom:14px;}
        .meta td{padding:4px 6px;border:1px solid #e2e5ec;font-size:10px;}
        .meta td.lbl{background:#f8fafc;color:#64748b;font-weight:bold;width:22%;text-transform:uppercase;font-size:9px;}
        .kra{border:1px solid #e2e5ec;margin-bottom:10px;}
        .kra-head{background:#8b5cf6;color:#fff;padding:7px 10px;font-weight:bold;font-size:11px;}
        .kra-head .w{float:right;background:rgba(255,255,255,.22);padding:1px 8px;border-radius:10px;font-size:10px;}
        .kra-body{padding:8px 10px;}
        .kra-desc{color:#64748b;font-size:10px;margin-bottom:6px;}
        table.kpis{width:100%;border-collapse:collapse;font-size:10px;}
        table.kpis th{background:#f1f5f9;border:1px solid #e2e5ec;padding:5px 7px;text-align:left;color:#475569;}
        table.kpis td{border:1px solid #e2e5ec;padding:5px 7px;}
        table.kpis td.t{color:#6d28d9;font-weight:bold;}
        .footer{margin-top:18px;padding-top:8px;border-top:1px solid #e2e5ec;color:#94a3b8;font-size:9px;text-align:center;}
    </style>
</head>
<body>
    <h1>KRA / KPI — {{ $gen->job_role }}</h1>
    <div class="sub">Generated on {{ $gen->created_at->format('d M Y, h:i A') }} · Reference #{{ $gen->id }}</div>

    <h2>Key Result Areas &amp; Performance Indicators</h2>

    @foreach($kras as $idx => $kra)
    <div class="kra">
        <div class="kra-head">
            KRA {{ $idx + 1 }}: {{ $kra['kra'] }}
            <span class="w">{{ $kra['weightage'] }}%</span>
        </div>
        <div class="kra-body">
            <div class="kra-desc">{{ $kra['description'] }}</div>
            <table class="kpis">
                <thead><tr><th width="50%">KPI / Metric</th><th width="30%">Target</th><th width="20%">Frequency</th></tr></thead>
                <tbody>
                @foreach($kra['kpis'] as $kpi)
                <tr>
                    <td>{{ $kpi['metric'] }}</td>
                    <td class="t">{{ $kpi['target'] }}</td>
                    <td>{{ $kpi['frequency'] }}</td>
                </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    @endforeach

    <div class="footer">Generated by HRMS Growth Review · KRA / KPI Generator</div>
</body>
</html>
